# Generated by Django 5.0.2 on 2024-02-20 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_kz', models.CharField(max_length=255, verbose_name='На казахском')),
                ('word_ru', models.CharField(max_length=255, verbose_name='На русском')),
                ('word_en', models.CharField(max_length=255, verbose_name='На английском')),
            ],
            options={
                'verbose_name': 'Слово',
                'verbose_name_plural': 'Слова',
            },
        ),
        migrations.CreateModel(
            name='WorkingClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название класса')),
            ],
            options={
                'verbose_name': 'Класс',
                'verbose_name_plural': 'Классы',
            },
        ),
        migrations.CreateModel(
            name='Voice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice_kz', models.FileField(upload_to='voice/kz/', verbose_name='На казахском')),
                ('voice_ru', models.FileField(upload_to='voice/ru/', verbose_name='На русском')),
                ('voice_en', models.FileField(upload_to='voice/kz/', verbose_name='На английском')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='langs_app.word', verbose_name='Слово')),
            ],
            options={
                'verbose_name': 'Произношение',
                'verbose_name_plural': 'Произношения',
            },
        ),
        migrations.CreateModel(
            name='FullData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='word/images/', verbose_name='Изображение')),
                ('voice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='langs_app.voice', verbose_name='Произношение')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='langs_app.word', verbose_name='Слово')),
                ('working_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='langs_app.workingclass', verbose_name='Класс')),
            ],
            options={
                'verbose_name': 'Итог',
                'verbose_name_plural': 'Итоги',
            },
        ),
    ]
