# Generated by Django 5.0.2 on 2024-02-20 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('langs_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workingclass',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
    ]
